

/* Create Tables */

CREATE TABLE SHOCHU
(
	SHOCHU_ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT '焼酎ID',
	SHOCHU_NAME VARCHAR(255) NOT NULL COMMENT '焼酎名',
	PRIMARY KEY (SHOCHU_ID)
) COMMENT = '焼酎';



