

/* Create Tables */

CREATE TABLE NIHONSHU
(
	NIHONSHU_ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT '日本酒ID',
	NIHONSHU_NAME VARCHAR(255) NOT NULL COMMENT '日本酒名',
	PRIMARY KEY (NIHONSHU_ID)
) COMMENT = '日本酒';



